# Model Configuration
model:
  name: 'facebook/detr-resnet-50'
  lr: 1e-4
  lr_backbone: 1e-5
  weight_decay: 1e-4

# Dataset Configuration
dataset:
  train_dir: 'detr-data/train'
  val_dir: 'detr-data/valid'
  test_dir: 'detr-data/test'
  annotation_file: '_annotations.coco.json'
  batch_size: 4
  num_workers: 4

# Training Configuration
training:
  max_epochs: 2
  gradient_clip_val: 0.1
  accumulate_grad_batches: 8
  log_every_n_steps: 5
  checkpoint_dir: 'checkpoints'

# Inference Configuration
inference:
  confidence_threshold: 0.5
  iou_threshold: 0.8
  save_visualizations: True
  visualization_dir: 'visualizations'
